### PR TITLE
EthIndia: Submission for project ArQuest

### PR DESCRIPTION
**Pull request by arminvoid**

### CODE REVIEW

**Comment by arminvoid** [comment]
@mbeacom This is our submission for the EthIndia. We emerged as one of the winning teams.
ArQuest builds on top of 2 popular open source projects - Aragon and Request Network.
Here is our demo video: https://youtu.be/E0p5Bjhkb30 - Hope you like it.

Please assist me with the next steps so that you can evaluate if we are eligible for the [bounty](https://gitcoin.co/issue/gitcoinco/ethindia/1/937).
Thank you.

**Comment by mbeacom** [comment]
@atvanguard Can you please `submit work` on the bounty:  https://gitcoin.co/issue/gitcoinco/ethindia/1/937 - Your team was selected for first place!

Thanks for your participation!

**Comment by atvanguard** [comment]
Thanks @mbeacom
I "started work" but don't see a submit work option. Can you help? Thanks.

**Comment by arminvoid** [comment]
Thanks @mbeacom 
I reopened this PR and submitted work on the bounty.

**Comment by arminvoid** [comment]
@mbeacom I would appreciate an update on this one.
Thank you.

**Pull request closed without merging**
